// Code generated by protoc-gen-go. DO NOT EDIT.
// source: s2s.proto

package s2sproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SSCmd int32

const (
	SSCmd_INVALID_CMD          SSCmd = 0
	SSCmd_REQ_CLUSTER_REQUEST  SSCmd = 10000
	SSCmd_RSP_CLUSTER_RESPONSE SSCmd = 10001
)

var SSCmd_name = map[int32]string{
	0:     "INVALID_CMD",
	10000: "REQ_CLUSTER_REQUEST",
	10001: "RSP_CLUSTER_RESPONSE",
}

var SSCmd_value = map[string]int32{
	"INVALID_CMD":          0,
	"REQ_CLUSTER_REQUEST":  10000,
	"RSP_CLUSTER_RESPONSE": 10001,
}

func (x SSCmd) String() string {
	return proto.EnumName(SSCmd_name, int32(x))
}

func (SSCmd) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_953aa047daafed82, []int{0}
}

type SSError int32

const (
	SSError_OK              SSError = 0
	SSError_ERR_RPC_TIMEOUT SSError = -10001
)

var SSError_name = map[int32]string{
	0:      "OK",
	-10001: "ERR_RPC_TIMEOUT",
}

var SSError_value = map[string]int32{
	"OK":              0,
	"ERR_RPC_TIMEOUT": -10001,
}

func (x SSError) String() string {
	return proto.EnumName(SSError_name, int32(x))
}

func (SSError) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_953aa047daafed82, []int{1}
}

type ReqClusterRequest struct {
	SrcCluster           string   `protobuf:"bytes,1,opt,name=SrcCluster,proto3" json:"SrcCluster,omitempty"`
	SrcService           string   `protobuf:"bytes,2,opt,name=SrcService,proto3" json:"SrcService,omitempty"`
	DstService           string   `protobuf:"bytes,3,opt,name=DstService,proto3" json:"DstService,omitempty"`
	Session              uint32   `protobuf:"varint,4,opt,name=Session,proto3" json:"Session,omitempty"`
	Request              []byte   `protobuf:"bytes,5,opt,name=Request,proto3" json:"Request,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqClusterRequest) Reset()         { *m = ReqClusterRequest{} }
func (m *ReqClusterRequest) String() string { return proto.CompactTextString(m) }
func (*ReqClusterRequest) ProtoMessage()    {}
func (*ReqClusterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_953aa047daafed82, []int{0}
}

func (m *ReqClusterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqClusterRequest.Unmarshal(m, b)
}
func (m *ReqClusterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqClusterRequest.Marshal(b, m, deterministic)
}
func (m *ReqClusterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqClusterRequest.Merge(m, src)
}
func (m *ReqClusterRequest) XXX_Size() int {
	return xxx_messageInfo_ReqClusterRequest.Size(m)
}
func (m *ReqClusterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqClusterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReqClusterRequest proto.InternalMessageInfo

func (m *ReqClusterRequest) GetSrcCluster() string {
	if m != nil {
		return m.SrcCluster
	}
	return ""
}

func (m *ReqClusterRequest) GetSrcService() string {
	if m != nil {
		return m.SrcService
	}
	return ""
}

func (m *ReqClusterRequest) GetDstService() string {
	if m != nil {
		return m.DstService
	}
	return ""
}

func (m *ReqClusterRequest) GetSession() uint32 {
	if m != nil {
		return m.Session
	}
	return 0
}

func (m *ReqClusterRequest) GetRequest() []byte {
	if m != nil {
		return m.Request
	}
	return nil
}

type RspClusterResponse struct {
	SrcCluster           string   `protobuf:"bytes,1,opt,name=SrcCluster,proto3" json:"SrcCluster,omitempty"`
	SrcService           string   `protobuf:"bytes,2,opt,name=SrcService,proto3" json:"SrcService,omitempty"`
	DstService           string   `protobuf:"bytes,3,opt,name=DstService,proto3" json:"DstService,omitempty"`
	Session              uint32   `protobuf:"varint,4,opt,name=Session,proto3" json:"Session,omitempty"`
	Response             []byte   `protobuf:"bytes,5,opt,name=Response,proto3" json:"Response,omitempty"`
	ErrMsg               string   `protobuf:"bytes,6,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RspClusterResponse) Reset()         { *m = RspClusterResponse{} }
func (m *RspClusterResponse) String() string { return proto.CompactTextString(m) }
func (*RspClusterResponse) ProtoMessage()    {}
func (*RspClusterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_953aa047daafed82, []int{1}
}

func (m *RspClusterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspClusterResponse.Unmarshal(m, b)
}
func (m *RspClusterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspClusterResponse.Marshal(b, m, deterministic)
}
func (m *RspClusterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspClusterResponse.Merge(m, src)
}
func (m *RspClusterResponse) XXX_Size() int {
	return xxx_messageInfo_RspClusterResponse.Size(m)
}
func (m *RspClusterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RspClusterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RspClusterResponse proto.InternalMessageInfo

func (m *RspClusterResponse) GetSrcCluster() string {
	if m != nil {
		return m.SrcCluster
	}
	return ""
}

func (m *RspClusterResponse) GetSrcService() string {
	if m != nil {
		return m.SrcService
	}
	return ""
}

func (m *RspClusterResponse) GetDstService() string {
	if m != nil {
		return m.DstService
	}
	return ""
}

func (m *RspClusterResponse) GetSession() uint32 {
	if m != nil {
		return m.Session
	}
	return 0
}

func (m *RspClusterResponse) GetResponse() []byte {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *RspClusterResponse) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type SSMsg struct {
	Cmd SSCmd `protobuf:"varint,1,opt,name=cmd,proto3,enum=s2sproto.SSCmd" json:"cmd,omitempty"`
	// Types that are valid to be assigned to Msg:
	//	*SSMsg_ClusterRequest
	//	*SSMsg_ClusterResponse
	Msg                  isSSMsg_Msg `protobuf_oneof:"Msg"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SSMsg) Reset()         { *m = SSMsg{} }
func (m *SSMsg) String() string { return proto.CompactTextString(m) }
func (*SSMsg) ProtoMessage()    {}
func (*SSMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_953aa047daafed82, []int{2}
}

func (m *SSMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SSMsg.Unmarshal(m, b)
}
func (m *SSMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SSMsg.Marshal(b, m, deterministic)
}
func (m *SSMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SSMsg.Merge(m, src)
}
func (m *SSMsg) XXX_Size() int {
	return xxx_messageInfo_SSMsg.Size(m)
}
func (m *SSMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_SSMsg.DiscardUnknown(m)
}

var xxx_messageInfo_SSMsg proto.InternalMessageInfo

func (m *SSMsg) GetCmd() SSCmd {
	if m != nil {
		return m.Cmd
	}
	return SSCmd_INVALID_CMD
}

type isSSMsg_Msg interface {
	isSSMsg_Msg()
}

type SSMsg_ClusterRequest struct {
	ClusterRequest *ReqClusterRequest `protobuf:"bytes,100,opt,name=cluster_request,json=clusterRequest,proto3,oneof"`
}

type SSMsg_ClusterResponse struct {
	ClusterResponse *RspClusterResponse `protobuf:"bytes,101,opt,name=cluster_response,json=clusterResponse,proto3,oneof"`
}

func (*SSMsg_ClusterRequest) isSSMsg_Msg() {}

func (*SSMsg_ClusterResponse) isSSMsg_Msg() {}

func (m *SSMsg) GetMsg() isSSMsg_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *SSMsg) GetClusterRequest() *ReqClusterRequest {
	if x, ok := m.GetMsg().(*SSMsg_ClusterRequest); ok {
		return x.ClusterRequest
	}
	return nil
}

func (m *SSMsg) GetClusterResponse() *RspClusterResponse {
	if x, ok := m.GetMsg().(*SSMsg_ClusterResponse); ok {
		return x.ClusterResponse
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SSMsg) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SSMsg_ClusterRequest)(nil),
		(*SSMsg_ClusterResponse)(nil),
	}
}

func init() {
	proto.RegisterEnum("s2sproto.SSCmd", SSCmd_name, SSCmd_value)
	proto.RegisterEnum("s2sproto.SSError", SSError_name, SSError_value)
	proto.RegisterType((*ReqClusterRequest)(nil), "s2sproto.ReqClusterRequest")
	proto.RegisterType((*RspClusterResponse)(nil), "s2sproto.RspClusterResponse")
	proto.RegisterType((*SSMsg)(nil), "s2sproto.SSMsg")
}

func init() { proto.RegisterFile("s2s.proto", fileDescriptor_953aa047daafed82) }

var fileDescriptor_953aa047daafed82 = []byte{
	// 382 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x91, 0x5f, 0xae, 0xd2, 0x40,
	0x14, 0xc6, 0x3b, 0x17, 0xe9, 0xbd, 0xf7, 0xa0, 0xb4, 0x8e, 0xc6, 0x54, 0x25, 0xa6, 0xf2, 0xd4,
	0xf0, 0x80, 0x49, 0x5d, 0x81, 0x96, 0x31, 0x34, 0xd2, 0x02, 0x67, 0x8a, 0xaf, 0x4d, 0x6c, 0x27,
	0x84, 0x44, 0x28, 0xcc, 0x14, 0xd7, 0xa1, 0xab, 0xf0, 0xd9, 0x2d, 0x18, 0xf7, 0xe3, 0x12, 0x34,
	0x2d, 0x53, 0xfe, 0x84, 0x05, 0xd8, 0xa7, 0x9e, 0xef, 0x37, 0xf9, 0xf2, 0x9b, 0x39, 0x70, 0xaf,
	0x7c, 0x35, 0xdc, 0xca, 0xa2, 0x2c, 0xe8, 0x9d, 0xf2, 0x55, 0xfd, 0xd7, 0xff, 0x41, 0xe0, 0x31,
	0x8a, 0x5d, 0xf0, 0x65, 0xaf, 0x4a, 0x21, 0x51, 0xec, 0xf6, 0x42, 0x95, 0xf4, 0x15, 0x00, 0x97,
	0x99, 0x0e, 0x1d, 0xe2, 0x12, 0xef, 0x1e, 0xcf, 0x12, 0xcd, 0xb9, 0x90, 0x5f, 0x57, 0x99, 0x70,
	0x6e, 0x8e, 0x5c, 0x27, 0x15, 0x1f, 0xa9, 0xb2, 0xe1, 0xad, 0x03, 0x3f, 0x25, 0xd4, 0x81, 0x5b,
	0x2e, 0x94, 0x5a, 0x15, 0x1b, 0xe7, 0x81, 0x4b, 0xbc, 0x47, 0xd8, 0x8c, 0x15, 0xd1, 0x12, 0x4e,
	0xdb, 0x25, 0xde, 0x43, 0x6c, 0xc6, 0xfe, 0x2f, 0x02, 0x14, 0xd5, 0xf6, 0x68, 0xaa, 0xb6, 0xc5,
	0x46, 0x89, 0xff, 0xa8, 0xfa, 0x02, 0xee, 0x1a, 0x0b, 0xed, 0x7a, 0x9c, 0xe9, 0x33, 0x30, 0x99,
	0x94, 0x91, 0x5a, 0x3a, 0x66, 0xdd, 0xa8, 0xa7, 0xfe, 0x6f, 0x02, 0x6d, 0xce, 0x23, 0xb5, 0xa4,
	0xaf, 0xa1, 0x95, 0xad, 0xf3, 0x5a, 0xb8, 0xeb, 0x5b, 0xc3, 0x66, 0x21, 0x43, 0xce, 0x83, 0x75,
	0x8e, 0x15, 0xa3, 0x1f, 0xc0, 0xca, 0x0e, 0xb7, 0x48, 0xa5, 0x7e, 0x93, 0xdc, 0x25, 0x5e, 0xc7,
	0x7f, 0x79, 0x3a, 0x7e, 0xb5, 0xbb, 0xb1, 0x81, 0xdd, 0xec, 0x72, 0x9b, 0x21, 0xd8, 0xa7, 0x1e,
	0x2d, 0x2c, 0xea, 0xa2, 0xde, 0x59, 0xd1, 0xd5, 0xd3, 0x8e, 0x0d, 0xb4, 0xb2, 0xcb, 0xe8, 0x7d,
	0x1b, 0x5a, 0x91, 0x5a, 0x0e, 0xa2, 0xea, 0x16, 0xc1, 0x3a, 0xa7, 0x16, 0x74, 0xc2, 0xf8, 0xd3,
	0xbb, 0x49, 0x38, 0x4a, 0x83, 0x68, 0x64, 0x1b, 0xd4, 0x81, 0x27, 0xc8, 0xe6, 0x69, 0x30, 0x59,
	0xf0, 0x84, 0x61, 0x8a, 0x6c, 0xbe, 0x60, 0x3c, 0xb1, 0xbf, 0xc5, 0xf4, 0x39, 0x3c, 0x45, 0x3e,
	0x3b, 0x23, 0x7c, 0x36, 0x8d, 0x39, 0xb3, 0xbf, 0xc7, 0x83, 0x37, 0x70, 0xcb, 0x39, 0x93, 0xb2,
	0x90, 0xd4, 0x84, 0x9b, 0xe9, 0x47, 0xdb, 0xa0, 0x3d, 0xb0, 0x18, 0x62, 0x8a, 0xb3, 0x20, 0x4d,
	0xc2, 0x88, 0x4d, 0x17, 0x89, 0xfd, 0xe7, 0xe7, 0xdf, 0xc3, 0x47, 0x3e, 0x9b, 0xb5, 0xf3, 0xdb,
	0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x2f, 0x40, 0x62, 0xea, 0xd3, 0x02, 0x00, 0x00,
}
